<?php

namespace Database\Factories;

use App\Models\Complaint;
use App\Models\SchoolYearSemester;
use App\Models\User;
use App\Models\Violation;
use Database\Factories\Concerns\GeneratesSampleFiles;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\File;
use Carbon\Carbon;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Complaint>
 */
class ComplaintFactory extends Factory
{
    use GeneratesSampleFiles;

    /**
     * Define the model's default state.
     *
     * Note: this only fills the complaint table's own columns. The subject(s)
     * of the complaint live in the separate complaint_subject table and are
     * not something a single-model factory can set — wire those up after
     * creating the complaint (see database/seeders/ComplaintSeeder.php).
     * The one complaint-wide PDF (one form, listing every complainee) is
     * generated by the seeder once all of a complaint's subjects exist.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $violation = Violation::inRandomOrder()->first();
        $complainant = User::inRandomOrder()->first();

        $createdAt = $this->faker->dateTimeBetween('-1 year', 'now');
        $confirmedAt = Carbon::parse($createdAt)->addDays(rand(1, 5));
        // Weighted toward "resolved" — that's the only status ML behavioural
        // analysis and the violation-history views have anything to work
        // with, so a low resolved share left most students with too little
        // data to produce a meaningful/varied prediction.
        $status = $this->faker->randomElement(['pending', 'ongoing', 'ongoing', 'resolved', 'resolved', 'resolved', 'resolved', 'rejected']);
        $resolvedAt = $status === 'resolved' ? Carbon::parse($confirmedAt)->addDays(rand(1, 10)) : null;

        // Matches the real "{MMDDYY}{daily-seq}" format from
        // GeneratesSequenceCode/ComplaintController::generateComplaintNumber().
        $prefix = Carbon::parse($createdAt)->format('mdy');
        $sequence = Complaint::where('complaint_number', 'like', "{$prefix}%")->count() + 1;

        return [
            'complaint_number' => $prefix . str_pad($sequence, 2, '0', STR_PAD_LEFT),
            'case_number' => $status !== 'pending' ? $this->faker->unique()->numberBetween(1000, 9999) : null,
            'complainant_id' => $complainant?->id,
            'incident_id' => $violation?->id,
            'complaint_description' => self::randomComplaintDescription($violation),
            'complaint_evidences' => null, // filled in by configure() below, once the folder/files exist
            // One shared narrative per complaint (not per complainee) —
            // matches the real resolve flow (ViolationController::multipleViolationStore()).
            'incident_summary' => $status === 'resolved' ? $this->faker->sentence(10) : null,
            'rejected_reason' => $status === 'rejected' ? $this->faker->sentence(8) : null,
            'rejected_at' => $status === 'rejected' ? $confirmedAt : null,
            'confirmed_at' => $status !== 'pending' ? $confirmedAt : null,
            'complaint_status' => $status,
            'resolved_at' => $resolvedAt,
            // offense_issued_at is what the real resolve flow
            // (ViolationController::multipleViolationStore()) actually
            // writes and what the view-complaint-modal "Resolved Since"
            // stat reads — mirror resolved_at here so seeded resolved
            // complaints display that stat too.
            'offense_issued_at' => $resolvedAt,
            'archived_at' => in_array($status, ['resolved', 'rejected']) ? Carbon::parse($confirmedAt)->addYears(5) : null,
            'school_year_semester_id' => SchoolYearSemester::idForDate($createdAt),
            'confirmed_school_year_semester_id' => $status !== 'pending' ? SchoolYearSemester::idForDate($confirmedAt) : null,
            'resolved_school_year_semester_id' => $resolvedAt ? SchoolYearSemester::idForDate($resolvedAt) : null,
            'rejected_school_year_semester_id' => $status === 'rejected' ? SchoolYearSemester::idForDate($confirmedAt) : null,
            'created_at' => $createdAt,
        ];
    }

    /**
     * Force a fully-consistent resolved complaint — recomputes every date
     * field that depends on the status instead of just overwriting
     * `complaint_status` on top of whatever random status definition()
     * already computed the other fields for (which would leave e.g.
     * resolved_at null on a complaint marked resolved).
     */
    public function resolved(): static
    {
        return $this->state(function (array $attributes) {
            $createdAt = $attributes['created_at'] ?? $this->faker->dateTimeBetween('-1 year', 'now');
            $confirmedAt = Carbon::parse($createdAt)->addDays(rand(1, 5));
            $resolvedAt = Carbon::parse($confirmedAt)->addDays(rand(1, 10));

            return [
                'complaint_status' => 'resolved',
                'case_number' => $this->faker->unique()->numberBetween(1000, 9999),
                'incident_summary' => $this->faker->sentence(10),
                'rejected_reason' => null,
                'rejected_at' => null,
                'confirmed_at' => $confirmedAt,
                'resolved_at' => $resolvedAt,
                'offense_issued_at' => $resolvedAt,
                'archived_at' => Carbon::parse($confirmedAt)->addYears(5),
                'school_year_semester_id' => SchoolYearSemester::idForDate($createdAt),
                'confirmed_school_year_semester_id' => SchoolYearSemester::idForDate($confirmedAt),
                'resolved_school_year_semester_id' => SchoolYearSemester::idForDate($resolvedAt),
                'rejected_school_year_semester_id' => null,
                'created_at' => $createdAt,
            ];
        });
    }

    /**
     * Faker's default paragraph()/sentence() generate Latin lorem-ipsum —
     * fine for most seeded text, but complaint_description is edited
     * through a rich text editor (real HTML in the DB) and is the exact
     * field Word2Vec complaint-context matching analyzes
     * (ComplaintController::viewComplaint() posts it as `complaint_text`
     * to /python/complaint/context). Lorem-ipsum has no real English words
     * for the pretrained Word2Vec vocabulary to embed, so that feature had
     * nothing meaningful to match against in seeded data. These templates
     * are real English/Tagalog/Taglish sentences (a Philippine school's
     * actual complainant mix) with the violation's own keyword woven in,
     * so the seeded text both reads like a real complaint and gives
     * Word2Vec something genuine to match against the correct violation.
     */
    public static function randomComplaintDescription(?Violation $violation): string
    {
        $templates = [
            // English
            'I am filing this complaint to report an incident involving {keyword} that occurred during school hours.',
            'This report is to formally document an incident related to {keyword} witnessed inside the campus.',
            'I would like to bring to your attention a case of {keyword} involving the student mentioned in this report.',
            'As a concerned member of the school community, I am reporting an incident concerning {keyword}.',
            'The following complaint details an incident of {keyword} that requires disciplinary action.',
            'I witnessed the student engaged in {keyword} and I believe this needs to be addressed immediately.',
            // Tagalog
            'Nais kong ireport ang isang insidente tungkol sa {keyword} na naganap sa loob ng paaralan.',
            'Ang report na ito ay tungkol sa nasaksihan kong {keyword} sa loob ng eskwelahan.',
            'Bilang guro, nais kong ipaalam ang tungkol sa {keyword} na ginawa ng estudyante.',
            'Ito po ay opisyal na reklamo tungkol sa {keyword} na naganap kamakailan lamang.',
            'Kagaya po ng aking nasaksihan, ang estudyante ay sangkot sa {keyword} noong nakaraang araw.',
            // Taglish
            'Gusto ko lang i-report yung nangyari na may kinalaman sa {keyword} dito sa school.',
            'Sobrang concerned ako dahil may nasaksihan akong {keyword} sa loob ng campus.',
            'This is to formally report na may {keyword} na naganap involving the student.',
            'Grabe po, na-witness ko mismo yung {keyword} kanina lang sa school premises.',
            'Alarming po talaga yung {keyword} na nangyari, kaya gusto ko i-report agad ito.',
        ];

        $paragraphs = [];
        for ($i = 0; $i < 2; $i++) {
            $sentence = str_replace(
                '{keyword}',
                self::pickComplaintKeyword($violation),
                $templates[array_rand($templates)]
            );
            $paragraphs[] = "<p>{$sentence}</p>";
        }

        return implode('', $paragraphs);
    }

    private static function pickComplaintKeyword(?Violation $violation): string
    {
        $keywords = $violation?->keywords ?? [];

        if (! empty($keywords)) {
            return $keywords[array_rand($keywords)];
        }

        return $violation ? strtolower($violation->violation_name) : 'misconduct';
    }

    public function configure(): static
    {
        return $this->afterCreating(function (Complaint $complaint) {
            $folder = storage_path("app/private/complaints/complaint-{$complaint->complaint_number}");
            File::ensureDirectoryExists("{$folder}/evidences");

            $count = random_int(1, 3);
            $evidences = [];
            for ($i = 1; $i <= $count; $i++) {
                $fileName = "{$i}-{$complaint->complaint_number}.jpg";
                $this->makePlaceholderImage("{$folder}/evidences/{$fileName}", 'Complaint Evidence');
                $evidences[] = ['type' => 'pic', 'file' => $fileName];
            }

            $complaint->update(['complaint_evidences' => json_encode($evidences)]);
        });
    }
}
