<?php

namespace Database\Factories;

use App\Models\Referral;
use App\Models\SchoolYearSemester;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\File;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Referral>
 *
 * Note: this only fills the referral table's own columns. The referred
 * student(s) live in the separate referral_referred_student table and are
 * not something a single-model factory can set — wire those up after
 * creating the referral (see database/seeders/ReferralSeeder.php). Their
 * per-student PDF is generated by ReferralReferredStudentFactory instead,
 * once the student is known.
 */
class ReferralFactory extends Factory
{
    public function definition(): array
    {
        $teachingStaff = User::where('role', 'teaching_staff')->inRandomOrder()->first();
        $subAdmin = User::where('role', 'sub_admin')->inRandomOrder()->first();

        // Most referrals are filed by teaching staff — the normal case,
        // going through the prefect's pending -> approve/reject workflow.
        // A prefect filing their own referral is the minority case, and
        // (per ReferralController::store()) is auto-approved the instant
        // it's created, so it can never end up pending/rejected/revoked.
        $referrer = ($teachingStaff && (! $subAdmin || $this->faker->boolean(85)))
            ? $teachingStaff
            : ($subAdmin ?? $teachingStaff ?? User::inRandomOrder()->first());

        $createdAt = $this->faker->dateTimeBetween('-1 year', 'now');

        if ($referrer?->role === 'sub_admin') {
            $status = 'approved';
            $confirmedAt = $createdAt;
            $rejectedAt = null;
            $revokedAt = null;
        } else {
            $status = $this->faker->randomElement(['pending', 'approved', 'approved', 'rejected', 'revoked']);
            $confirmedAt = $status === 'approved' ? Carbon::parse($createdAt)->addDays(rand(1, 5)) : null;
            $rejectedAt = $status === 'rejected' ? Carbon::parse($createdAt)->addDays(rand(1, 5)) : null;
            // Matches revokeReferral()'s real window — only reachable while
            // still pending and unconfirmed, so this always happens soon
            // after filing, never days later.
            $revokedAt = $status === 'revoked' ? Carbon::parse($createdAt)->addHours(rand(1, 48)) : null;
        }

        $retentionYears = (int) config('app.archive_retention_years', 5);
        $archivedAt = match (true) {
            $confirmedAt !== null => Carbon::parse($confirmedAt)->addYears($retentionYears),
            $rejectedAt !== null => Carbon::parse($rejectedAt)->addYears($retentionYears),
            $revokedAt !== null => Carbon::parse($revokedAt)->addYears($retentionYears),
            default => null,
        };

        // Matches the real "{MMDDYY}{daily-seq}" format from
        // GeneratesSequenceCode/ReferralController.
        $prefix = Carbon::parse($createdAt)->format('mdy');
        $sequence = Referral::where('referral_number', 'like', "{$prefix}%")->count() + 1;

        return [
            'teaching_staff_id' => $referrer?->id,
            'referral_number' => $prefix . str_pad($sequence, 2, '0', STR_PAD_LEFT),
            'reason_description' => $this->faker->paragraph(2),
            'referral_status' => $status,
            'rejected_reason' => $status === 'rejected' ? $this->faker->sentence(8) : null,
            'rejected_at' => $rejectedAt,
            'revoked_at' => $revokedAt,
            'send_to_guidance' => $this->faker->boolean(40) ? 1 : 0,
            'confirmed_at' => $confirmedAt,
            'archived_at' => $archivedAt,
            'school_year_semester_id' => SchoolYearSemester::idForDate($createdAt),
            'confirmed_school_year_semester_id' => $confirmedAt ? SchoolYearSemester::idForDate($confirmedAt) : null,
            'rejected_school_year_semester_id' => $rejectedAt ? SchoolYearSemester::idForDate($rejectedAt) : null,
            'revoked_school_year_semester_id' => $revokedAt ? SchoolYearSemester::idForDate($revokedAt) : null,
            'created_at' => $createdAt,
        ];
    }

    public function configure(): static
    {
        return $this->afterCreating(function (Referral $referral) {
            File::ensureDirectoryExists(storage_path("app/private/referrals/referral-{$referral->referral_number}"));
        });
    }
}
